version: "3"
services:
  redis-server:
    image: redis
    ports:
     - "6379:6379"
  api:
    image: atos06/redis_pubsub_node_api
    ports:
      - "8000:8000"
    depends_on:
      - redis-server
  workers:
    image: atos06/redis_pubsub_node_workers:1.0
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8001-9000:5000"
    depends_on:
      - redis-server